name: element-lookup # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Search Engine for the Periodic Table # 79 char long summary
description: |
  Element Lookup, an app that serves as a search engine of the Periodic Table can help you in whatever
  chemistry homework. It shows the details of the element such as symbol, atomic number, atomic mass,
  appearance and the scientist who discovered it.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
 element-lookup:
   command: bin/element-lookup

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
